# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bloger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
