# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20191118_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Playground',
            new_name='ground',
        ),
    ]
