# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20191121_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('posted_by', models.CharField(max_length=30)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.Fitness_activities')),
            ],
        ),
    ]
