# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_blog_bloger'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='play.Profile'),
        ),
    ]
