# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20191121_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
