# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_auto_20191121_1354'),
        ('play', '0003_auto_20191121_1221'),
    ]

    operations = [
    ]
